"""Validate the self-describing schema of R ``mice`` evidence artifacts.

This validator intentionally verifies provenance and numerical hygiene only.
It does not compare Missingly output with R ``mice`` and must not be used to
claim algorithmic parity before a reviewed conformance manifest is added.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
import sys
from typing import Any, Mapping


_REQUIRED_KEYS = {
    "schema_version",
    "artifact_kind",
    "reference_tool",
    "reference_tool_version",
    "r_version",
    "platform",
    "method",
    "seed",
    "dataset_sha256",
    "source_script_sha256",
    "metrics",
}


def _is_sha256(value: object) -> bool:
    """Return whether ``value`` is a lowercase SHA-256 digest.

    Parameters
    ----------
    value : object
        Candidate digest value.

    Returns
    -------
    bool
        ``True`` only for lowercase 64-character hexadecimal strings.

    Examples
    --------
    >>> _is_sha256("a" * 64)
    True
    >>> _is_sha256("not-a-digest")
    False
    """
    return isinstance(value, str) and len(value) == 64 and all(
        character in "0123456789abcdef" for character in value
    )


def validate_reference(reference: Mapping[str, Any]) -> None:
    """Validate an evidence-only R ``mice`` artifact.

    Parameters
    ----------
    reference : mapping of str to Any
        Decoded JSON emitted by ``generate_mice_reference.R``.

    Returns
    -------
    None
        The function returns after all provenance and metric checks pass.

    Raises
    ------
    ValueError
        If the artifact schema, identity, or aggregate metric is invalid.

    Examples
    --------
    >>> artifact = {
    ...     "schema_version": 1, "artifact_kind": "evidence-only",
    ...     "reference_tool": "R mice", "reference_tool_version": "3.0",
    ...     "r_version": "4.4", "platform": "x86_64-pc-linux-gnu",
    ...     "method": "mice::mice(method='norm', m=3, maxit=5)", "seed": 1,
    ...     "dataset_sha256": "a" * 64, "source_script_sha256": "b" * 64,
    ...     "metrics": {"chain_1_mean_x1": 1.0},
    ... }
    >>> validate_reference(artifact)
    """
    if set(reference) != _REQUIRED_KEYS:
        raise ValueError("R mice evidence keys must match the published schema")
    if reference["schema_version"] != 1:
        raise ValueError("R mice evidence schema_version must be 1")
    if reference["artifact_kind"] != "evidence-only":
        raise ValueError("R mice evidence must be labelled evidence-only")
    if reference["reference_tool"] != "R mice":
        raise ValueError("R mice evidence was generated by an unexpected tool")
    if isinstance(reference["seed"], bool) or not isinstance(reference["seed"], int):
        raise ValueError("R mice evidence seed must be an integer")
    for field in (
        "reference_tool_version",
        "r_version",
        "platform",
        "method",
    ):
        if not isinstance(reference[field], str) or not reference[field].strip():
            raise ValueError(f"R mice evidence {field} must be a non-empty string")
    for field in ("dataset_sha256", "source_script_sha256"):
        if not _is_sha256(reference[field]):
            raise ValueError(f"R mice evidence {field} must be a SHA-256 digest")

    metrics = reference["metrics"]
    if not isinstance(metrics, Mapping) or not metrics:
        raise ValueError("R mice evidence must contain aggregate metrics")
    for name, value in metrics.items():
        if not isinstance(name, str) or not name.startswith("chain_"):
            raise ValueError("R mice evidence metric names must identify a chain")
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f"R mice evidence metric {name!r} must be numeric")
        if not math.isfinite(float(value)):
            raise ValueError(f"R mice evidence metric {name!r} must be finite")


def main(reference_path: Path) -> None:
    """Validate the JSON artifact at ``reference_path``.

    Parameters
    ----------
    reference_path : pathlib.Path
        Path to the scalar JSON evidence file emitted by the R generator.

    Returns
    -------
    None
        The process returns normally only for a valid evidence artifact.

    Examples
    --------
    >>> isinstance(Path("mice_reference.json"), Path)
    True
    """
    validate_reference(json.loads(reference_path.read_text(encoding="utf-8")))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("Usage: validate_mice_reference.py <reference.json>")
    main(Path(sys.argv[1]))
