"""Validate R ``mice`` evidence against reviewed, scoped scalar metrics.

The validator compares only R regeneration output with its committed R oracle.
It does not compare a Missingly algorithm with R ``mice`` and must not be used
to claim general algorithmic parity.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
import sys
from typing import Any, Mapping, Optional


_REQUIRED_KEYS = {
    "schema_version",
    "artifact_kind",
    "reference_tool",
    "reference_tool_version",
    "r_version",
    "platform",
    "method",
    "seed",
    "dataset_sha256",
    "source_script_sha256",
    "metrics",
}


def _is_sha256(value: object) -> bool:
    """Return whether ``value`` is a lowercase SHA-256 digest.

    Parameters
    ----------
    value : object
        Candidate digest value.

    Returns
    -------
    bool
        ``True`` only for lowercase 64-character hexadecimal strings.

    Examples
    --------
    >>> _is_sha256("a" * 64)
    True
    >>> _is_sha256("not-a-digest")
    False
    """
    return isinstance(value, str) and len(value) == 64 and all(
        character in "0123456789abcdef" for character in value
    )


def validate_reference(
    reference: Mapping[str, Any],
    manifest: Optional[Mapping[str, Any]] = None,
) -> None:
    """Validate an evidence-only R ``mice`` artifact.

    Parameters
    ----------
    reference : mapping of str to Any
        Decoded JSON emitted by ``generate_mice_reference.R``.
    manifest : mapping of str to Any, optional
        Reviewed benchmark manifest. When supplied, provenance fields and every
        scalar metric are checked against its recorded absolute tolerance.

    Returns
    -------
    None
        The function returns after all provenance and metric checks pass.

    Raises
    ------
    ValueError
        If the artifact schema, identity, or aggregate metric is invalid.

    Examples
    --------
    >>> artifact = {
    ...     "schema_version": 1, "artifact_kind": "evidence-only",
    ...     "reference_tool": "R mice", "reference_tool_version": "3.0",
    ...     "r_version": "4.4", "platform": "x86_64-pc-linux-gnu",
    ...     "method": "mice::mice(method='norm', m=3, maxit=5)", "seed": 1,
    ...     "dataset_sha256": "a" * 64, "source_script_sha256": "b" * 64,
    ...     "metrics": {"chain_1_mean_x1": 1.0},
    ... }
    >>> validate_reference(artifact)
    """
    if set(reference) != _REQUIRED_KEYS:
        raise ValueError("R mice evidence keys must match the published schema")
    if reference["schema_version"] != 1:
        raise ValueError("R mice evidence schema_version must be 1")
    if reference["artifact_kind"] != "evidence-only":
        raise ValueError("R mice evidence must be labelled evidence-only")
    if reference["reference_tool"] != "R mice":
        raise ValueError("R mice evidence was generated by an unexpected tool")
    if isinstance(reference["seed"], bool) or not isinstance(reference["seed"], int):
        raise ValueError("R mice evidence seed must be an integer")
    for field in (
        "reference_tool_version",
        "r_version",
        "platform",
        "method",
    ):
        if not isinstance(reference[field], str) or not reference[field].strip():
            raise ValueError(f"R mice evidence {field} must be a non-empty string")
    for field in ("dataset_sha256", "source_script_sha256"):
        if not _is_sha256(reference[field]):
            raise ValueError(f"R mice evidence {field} must be a SHA-256 digest")

    metrics = reference["metrics"]
    if not isinstance(metrics, Mapping) or not metrics:
        raise ValueError("R mice evidence must contain aggregate metrics")
    for name, value in metrics.items():
        if not isinstance(name, str) or not name.startswith("chain_"):
            raise ValueError("R mice evidence metric names must identify a chain")
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f"R mice evidence metric {name!r} must be numeric")
        if not math.isfinite(float(value)):
            raise ValueError(f"R mice evidence metric {name!r} must be finite")

    if manifest is not None:
        _validate_against_manifest(reference, manifest)


def _validate_against_manifest(
    reference: Mapping[str, Any],
    manifest: Mapping[str, Any],
) -> None:
    """Compare valid R evidence with a reviewed scalar oracle manifest.

    Parameters
    ----------
    reference : mapping of str to Any
        Schema-valid scalar evidence emitted by the R generator.
    manifest : mapping of str to Any
        Reviewed manifest containing identities, expected metrics, and absolute
        tolerances.

    Returns
    -------
    None
        Returns normally only when all locked identities and metrics agree.

    Raises
    ------
    ValueError
        If provenance differs, metric keys differ, or a metric exceeds its
        reviewed tolerance.

    Examples
    --------
    >>> _validate_against_manifest(
    ...     {"reference_tool": "R mice", "reference_tool_version": "1", "dataset_sha256": "a", "source_script_sha256": "b", "method": "m", "seed": 1, "metrics": {"x": 1.0}},
    ...     {"reference_tool": "R mice", "reference_tool_version": "1", "dataset_sha256": "a", "reference_script_sha256": "b", "method": "m", "seed": 1, "expected_metrics": {"x": 1.0}, "tolerances": {"x": 0.0}},
    ... )
    """
    identities = {
        "reference_tool": "reference_tool",
        "reference_tool_version": "reference_tool_version",
        "dataset_sha256": "dataset_sha256",
        "source_script_sha256": "reference_script_sha256",
        "method": "method",
        "seed": "seed",
    }
    for reference_key, manifest_key in identities.items():
        if reference[reference_key] != manifest.get(manifest_key):
            raise ValueError(
                f"R mice evidence {reference_key} does not match benchmark manifest"
            )

    expected = manifest.get("expected_metrics")
    tolerances = manifest.get("tolerances")
    if not isinstance(expected, Mapping) or not isinstance(tolerances, Mapping):
        raise ValueError("benchmark manifest must define expected metrics and tolerances")
    if set(reference["metrics"]) != set(expected) or set(expected) != set(tolerances):
        raise ValueError("R mice evidence metric keys must match benchmark manifest")
    for name, target in expected.items():
        actual = float(reference["metrics"][name])
        tolerance = float(tolerances[name])
        if not math.isfinite(float(target)) or not math.isfinite(tolerance) or tolerance < 0:
            raise ValueError("benchmark manifest contains an invalid metric tolerance")
        if abs(actual - float(target)) > tolerance:
            raise ValueError(
                f"R mice metric {name!r} differs from committed oracle: "
                f"actual={actual}, expected={target}, tolerance={tolerance}"
            )


def main(reference_path: Path, manifest_path: Optional[Path] = None) -> None:
    """Validate the JSON artifact at ``reference_path``.

    Parameters
    ----------
    reference_path : pathlib.Path
        Path to the scalar JSON evidence file emitted by the R generator.
    manifest_path : pathlib.Path, optional
        Reviewed benchmark manifest. Omitting it performs schema-only evidence
        validation, while CI supplies it for numerical oracle validation.

    Returns
    -------
    None
        The process returns normally only for a valid evidence artifact.

    Examples
    --------
    >>> isinstance(Path("mice_reference.json"), Path)
    True
    """
    manifest = None
    if manifest_path is not None:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    validate_reference(json.loads(reference_path.read_text(encoding="utf-8")), manifest)


if __name__ == "__main__":
    if len(sys.argv) not in (2, 3):
        raise SystemExit("Usage: validate_mice_reference.py <reference.json> [manifest.json]")
    main(Path(sys.argv[1]), Path(sys.argv[2]) if len(sys.argv) == 3 else None)
