"""HTML report generation for missing data analysis.

This module provides :func:`create_report`, which generates a
self-contained, standalone HTML report summarising all aspects of
missingness in a DataFrame.

All plots are generated with a non-interactive Matplotlib backend so the
function works correctly in headless CI environments and notebooks alike.

Compatibility
-------------
Requires Python 3.9+, pandas 2.0+, matplotlib, and jinja2.
"""

from __future__ import annotations

import base64
import warnings
from io import BytesIO
from typing import Optional

import matplotlib
matplotlib.use("Agg")  # headless backend -- must be set before pyplot import
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from jinja2 import Environment, FileSystemLoader

from .diagnostics import miss_case_summary, n_miss, pct_miss, mcar_test
from .visualise import matrix, bar, heatmap, vis_miss, upset


# ---------------------------------------------------------------------------
# i18n: UI label translations
# ---------------------------------------------------------------------------

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        # Page meta
        "title":                   "Missing Data Report",
        "subtitle":                "Automated missing data analysis",
        # Section headings
        "section_overview":        "Missing Values by Variable",
        "section_summary":         "Dataset Summary",
        "section_variables":       "Missing Values by Variable",
        "section_cases":           "Top 10 Rows by Missingness",
        "section_mcar":            "MCAR Test (Little\u2019s Test)",
        "section_recommendation":  "Imputation Recommendation",
        "section_plots":           "Visualisations",
        # Overview table columns
        "col_column":              "Column",
        "col_missing":             "Missing",
        "col_pct":                 "% Missing",
        "col_pct_bar":             "Distribution",
        "col_dtype":               "Type",
        "col_severity":            "Severity",
        # Summary stats table
        "stat_key":                "Statistic",
        "stat_value":              "Value",
        "stat_total_cells":        "Total cells",
        "stat_missing_cells":      "Missing cells",
        "stat_pct_missing":        "% Missing",
        "stat_cols_any":           "Columns with any missing",
        "stat_rows_any":           "Rows with any missing",
        "stat_complete_rows":      "Complete rows",
        # MCAR stat labels
        "stat_chi_square":         "Chi-square",
        "stat_df":                 "Degrees of Freedom",
        "stat_p_value":            "p-value",
        "stat_patterns":           "Missing Patterns",
        # Plot titles
        "plot_matrix":             "Missingness Matrix",
        "plot_bar":                "Missing Values per Column",
        "plot_heatmap":            "Missingness Correlation Heatmap",
        "plot_vismiss":            "Missing Pattern Overview",
        "plot_upset":              "Upset Plot",
        # Misc
        "no_missing":              "\u2713 No missing values detected in this DataFrame.",
        "generated_by":            "Generated by",
        "recommendation_icon":     "\U0001f4a1",
    },
    "fa": {
        "title":                   "\u06af\u0632\u0627\u0631\u0634 \u062f\u0627\u062f\u0647\u200c\u0647\u0627\u06cc \u063a\u0627\u06cc\u0628",
        "subtitle":                "\u062a\u062d\u0644\u06cc\u0644 \u062e\u0648\u062f\u06a9\u0627\u0631 \u063a\u06cc\u0628\u062a",
        "section_overview":        "\u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628 \u0628\u0647 \u062a\u0641\u06a9\u06cc\u06a9 \u0645\u062a\u063a\u06cc\u0631",
        "section_summary":         "\u062e\u0644\u0627\u0635\u0647 \u0645\u062c\u0645\u0648\u0639\u0647 \u062f\u0627\u062f\u0647",
        "section_variables":       "\u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628 \u0628\u0647 \u062a\u0641\u06a9\u06cc\u06a9 \u0645\u062a\u063a\u06cc\u0631",
        "section_cases":           "\u06f1\u06f0 \u0633\u0637\u0631 \u0628\u0627 \u0628\u06cc\u0634\u062a\u0631\u06cc\u0646 \u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628",
        "section_mcar":            "\u0622\u0632\u0645\u0648\u0646 MCAR (Little\u2019s Test)",
        "section_recommendation":  "\u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u062c\u0627\u06cc\u06af\u0632\u06cc\u0646\u06cc",
        "section_plots":           "\u0646\u0645\u0648\u062f\u0627\u0631\u0647\u0627",
        "col_column":              "\u0633\u062a\u0648\u0646",
        "col_missing":             "\u063a\u0627\u06cc\u0628",
        "col_pct":                 "\u062f\u0631\u0635\u062f \u063a\u06cc\u0628\u062a",
        "col_pct_bar":             "\u062a\u0648\u0632\u06cc\u0639",
        "col_dtype":               "\u0646\u0648\u0639",
        "col_severity":            "\u0634\u062f\u062a",
        "stat_key":                "\u0622\u0645\u0627\u0631",
        "stat_value":              "\u0645\u0642\u062f\u0627\u0631",
        "stat_total_cells":        "\u06a9\u0644 \u062e\u0627\u0646\u0647\u0647\u0627",
        "stat_missing_cells":      "\u062e\u0627\u0646\u0647\u0647\u0627\u06cc \u063a\u0627\u06cc\u0628",
        "stat_pct_missing":        "\u062f\u0631\u0635\u062f \u063a\u06cc\u0628\u062a",
        "stat_cols_any":           "\u0633\u062a\u0648\u0646\u200c\u0647\u0627\u06cc \u062f\u0627\u0631\u0627\u06cc \u063a\u06cc\u0628\u062a",
        "stat_rows_any":           "\u0633\u0637\u0631\u0647\u0627\u06cc \u062f\u0627\u0631\u0627\u06cc \u063a\u06cc\u0628\u062a",
        "stat_complete_rows":      "\u0633\u0637\u0631\u0647\u0627\u06cc \u06a9\u0627\u0645\u0644",
        "stat_chi_square":         "Chi-square",
        "stat_df":                 "\u062f\u0631\u062c\u0627\u062a \u0622\u0632\u0627\u062f\u06cc",
        "stat_p_value":            "p-value",
        "stat_patterns":           "\u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a",
        "plot_matrix":             "\u0645\u0627\u062a\u0631\u06cc\u0633 \u063a\u06cc\u0628\u062a",
        "plot_bar":                "\u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628 \u0628\u0647 \u0627\u0632\u0627\u06cc \u0633\u062a\u0648\u0646",
        "plot_heatmap":            "\u0647\u0645\u0628\u0633\u062a\u06af\u06cc \u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a",
        "plot_vismiss":            "\u0646\u0645\u0627\u06cc \u06a9\u0644\u06cc \u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a",
        "plot_upset":              "Upset Plot",
        "no_missing":              "\u2713 \u0647\u06cc\u0686 \u0645\u0642\u062f\u0627\u0631 \u063a\u0627\u06cc\u0628\u06cc \u062f\u0631 \u0627\u06cc\u0646 DataFrame \u06cc\u0627\u0641\u062a \u0646\u0634\u062f.",
        "generated_by":            "\u062a\u0648\u0644\u06cc\u062f\u0634\u062f\u0647 \u062a\u0648\u0633\u0637",
        "recommendation_icon":     "\U0001f4a1",
    },
    "de": {
        "title":                   "Bericht: Fehlende Daten",
        "subtitle":                "Automatisierte Fehlwert-Analyse",
        "section_overview":        "Fehlende Werte nach Variable",
        "section_summary":         "Datensatz\u00fcbersicht",
        "section_variables":       "Fehlende Werte nach Variable",
        "section_cases":           "Top 10 Zeilen nach Fehlenden Werten",
        "section_mcar":            "MCAR-Test (Little\u2019s Test)",
        "section_recommendation":  "Imputationsempfehlung",
        "section_plots":           "Visualisierungen",
        "col_column":              "Spalte",
        "col_missing":             "Fehlend",
        "col_pct":                 "% Fehlend",
        "col_pct_bar":             "Verteilung",
        "col_dtype":               "Typ",
        "col_severity":            "Schweregrad",
        "stat_key":                "Statistik",
        "stat_value":              "Wert",
        "stat_total_cells":        "Zellen gesamt",
        "stat_missing_cells":      "Fehlende Zellen",
        "stat_pct_missing":        "% Fehlend",
        "stat_cols_any":           "Spalten mit Fehlwerten",
        "stat_rows_any":           "Zeilen mit Fehlwerten",
        "stat_complete_rows":      "Vollst\u00e4ndige Zeilen",
        "stat_chi_square":         "Chi-Quadrat",
        "stat_df":                 "Freiheitsgrade",
        "stat_p_value":            "p-value",
        "stat_patterns":           "Fehlende Muster",
        "plot_matrix":             "Fehlende-Werte-Matrix",
        "plot_bar":                "Fehlende Werte pro Spalte",
        "plot_heatmap":            "Korrelations-Heatmap der Fehlenden",
        "plot_vismiss":            "Muster\u00fcbersicht",
        "plot_upset":              "Upset Plot",
        "no_missing":              "\u2713 Keine fehlenden Werte in diesem DataFrame gefunden.",
        "generated_by":            "Erstellt von",
        "recommendation_icon":     "\U0001f4a1",
    },
}

_RTL_LANGUAGES: frozenset[str] = frozenset({"fa", "ar", "he", "ur"})
_SUPPORTED_LANGUAGES: frozenset[str] = frozenset(_TRANSLATIONS)


def _get_labels(language: str) -> dict[str, str]:
    return _TRANSLATIONS.get(language, _TRANSLATIONS["en"])


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _fig_to_b64(fig: plt.Figure) -> str:
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=120)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def _safe_plot(plot_fn, df: pd.DataFrame, **kwargs) -> Optional[str]:
    """Call a plot function and return a base64 PNG string, or None on failure.

    Works for functions that return either a Figure or an Axes.
    On failure, emits a UserWarning and returns None so the report is
    still generated without the offending plot.

    Catches only specific, expected failure modes:
    - ``ImportError`` / ``ModuleNotFoundError``: optional matplotlib filter import.
    - ``TypeError``, ``ValueError``: bad arguments to the plot function.
    - ``RuntimeError``: matplotlib backend or rendering failure.
    - ``MemoryError``: frame too large to render.
    """
    try:
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", message=".*set_bad.*")
            try:
                import matplotlib as _mpl
                warnings.filterwarnings(
                    "ignore", category=_mpl.MatplotlibDeprecationWarning
                )
            except (ImportError, ModuleNotFoundError):
                pass

            result = plot_fn(df, **kwargs)

            # Accept both Axes and Figure returns
            if isinstance(result, plt.Figure):
                fig = result
            elif hasattr(result, "figure"):
                fig = result.figure
            else:
                fig = plt.gcf()

            b64 = _fig_to_b64(fig)
            plt.close(fig)
        return b64
    except (TypeError, ValueError, RuntimeError, MemoryError) as exc:
        warnings.warn(
            f"Plot {plot_fn.__name__!r} failed: {exc}", UserWarning, stacklevel=2
        )
        plt.close("all")
        return None


def _mcar_interpretation(p_value: float, overall_pct: float, lang: str = "en") -> dict:
    """Produce assumption-aware interpretation of Little's MCAR test.

    Parameters
    ----------
    p_value : float
        P-value from Little's MCAR test. A non-significant value is evidence
        insufficient to reject MCAR; it is not proof that data are MCAR.
    overall_pct : float
        Percentage of all values that are missing.
    lang : {"en", "fa", "de"}, default="en"
        Language used for human-readable details.

    Returns
    -------
    dict
        Mechanism evidence, explanatory text, and an analysis recommendation
        selected from missingness magnitude and explicit assumptions rather
        than an unidentifiable MAR/MNAR label.

    Examples
    --------
    >>> result = _mcar_interpretation(0.20, 12.0)
    >>> result["mechanism"]
    'MCAR not rejected'
    """
    import math

    is_fa = lang == "fa"
    is_de = lang == "de"

    if math.isnan(p_value):
        mechanism = "Unknown"
        if is_fa:
            mechanism_detail = (
                "\u0622\u0632\u0645\u0648\u0646 MCAR \u0642\u0627\u0628\u0644 \u0645\u062d\u0627\u0633\u0628\u0647 \u0646\u0628\u0648\u062f "
                "(\u062f\u0627\u062f\u0647 \u06a9\u0627\u0641\u06cc \u0646\u06cc\u0633\u062a \u06cc\u0627 \u0641\u0642\u0637 \u06cc\u06a9 \u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a \u0648\u062c\u0648\u062f \u062f\u0627\u0631\u062f). "
                "\u0633\u0627\u0632\u0648\u06a9\u0627\u0631 \u0646\u0627\u0645\u0634\u062e\u0635 \u0641\u0631\u0636 \u06a9\u0646\u06cc\u062f."
            )
        elif is_de:
            mechanism_detail = (
                "Der MCAR-Test konnte nicht berechnet werden "
                "(unzureichende Daten oder nur ein fehlendes Muster). "
                "Behandeln Sie den Mechanismus als unbekannt."
            )
        else:
            mechanism_detail = (
                "The MCAR test could not be computed (insufficient data or "
                "only one missing pattern). Treat the mechanism as unknown."
            )
    elif p_value > 0.05:
        mechanism = "MCAR not rejected"
        if is_fa:
            mechanism_detail = (
                f"p-value = {p_value:.4f} > 0.05: \u0641\u0631\u0636\u06cc\u0647 MCAR \u0631\u062f \u0646\u0634\u062f."
            )
        elif is_de:
            mechanism_detail = f"p-value = {p_value:.4f} > 0.05: MCAR kann nicht abgelehnt werden."
        else:
            mechanism_detail = (
                f"p-value = {p_value:.4f} > 0.05: cannot reject MCAR. "
                "This does not establish MCAR or justify single-value imputation for inference."
            )
    else:
        mechanism = "Evidence against MCAR"
        if is_fa:
            mechanism_detail = f"p-value = {p_value:.4f} \u2264 0.05: \u0641\u0631\u0636\u06cc\u0647 MCAR \u0631\u062f \u0634\u062f."
        elif is_de:
            mechanism_detail = f"p-value = {p_value:.4f} \u2264 0.05: MCAR wird abgelehnt."
        else:
            mechanism_detail = (
                f"p-value = {p_value:.4f} \u2264 0.05: MCAR is rejected. "
                "Observed data cannot distinguish MAR from MNAR."
            )

    if overall_pct < 5:
        recommendation = "Document assumptions and choose an analysis plan"
        recommendation_detail = (
            "Low missingness does not establish MCAR. Pre-specify the analysis and "
            "assess whether complete-case analysis is scientifically defensible."
        )
    elif overall_pct < 20:
        recommendation = "Multiple imputation or model-based analysis + sensitivity analysis"
        recommendation_detail = (
            "Choose an imputation or likelihood-based model from substantive knowledge "
            "and assess sensitivity to missing-data assumptions."
        )
    else:
        recommendation = "Multiple imputation + sensitivity analysis + domain review"
        recommendation_detail = (
            "High missingness requires a documented analysis plan, domain review, and "
            "sensitivity analysis; no observed-data diagnostic can rule out MNAR."
        )

    recommendation_translations = {
        "fa": {
            "Document assumptions and choose an analysis plan": (
                "ثبت فرض‌ها و انتخاب برنامه تحلیل",
                "کم‌بودن غیبت داده‌ها MCAR را اثبات نمی‌کند؛ تحلیل را از پیش مشخص کنید و اعتبار تحلیل موارد کامل را با دانش دامنه بسنجید.",
            ),
            "Multiple imputation or model-based analysis + sensitivity analysis": (
                "جایگزینی چندگانه یا تحلیل مدل‌محور همراه تحلیل حساسیت",
                "روش را بر پایه دانش دامنه انتخاب کنید و حساسیت نتیجه را نسبت به فرض‌های غیبت داده بررسی کنید.",
            ),
            "Multiple imputation + sensitivity analysis + domain review": (
                "جایگزینی چندگانه، تحلیل حساسیت و بازبینی تخصصی",
                "غیبت زیاد به برنامه تحلیل مستند، بازبینی تخصصی و تحلیل حساسیت نیاز دارد؛ هیچ آزمون مبتنی بر داده مشاهده‌شده MNAR را رد نمی‌کند.",
            ),
            "Complete-case analysis or mean/median imputation": (
                "تحلیل موارد کامل یا جایگزینی میانگین/میانه",
                "غیبت داده‌ها MCAR و کم‌تر از ۵٪ است؛ حذف سطرها احتمالاً سوگیری معناداری ایجاد نمی‌کند.",
            ),
            "KNN or MICE imputation": (
                "جایگزینی با KNN یا MICE",
                "غیبت داده‌ها MCAR اما متوسط است؛ KNN یا MICE ساختار آماری بیشتری را حفظ می‌کند.",
            ),
            "MICE imputation + sensitivity analysis": (
                "جایگزینی MICE همراه تحلیل حساسیت",
                "غیبت داده‌ها MCAR اما زیاد است؛ از MICE استفاده کنید و تحلیل حساسیت انجام دهید.",
            ),
            "MICE or Random Forest imputation": (
                "جایگزینی با MICE یا Random Forest",
                "غیبت داده‌ها MCAR نیست؛ روش‌های مدل‌محور MICE یا Random Forest توصیه می‌شوند.",
            ),
            "Random Forest or Gradient Boosting imputation + domain review": (
                "جایگزینی با Random Forest یا Gradient Boosting همراه بازبینی تخصصی",
                "غیبت داده‌ها MCAR نیست و نرخ آن زیاد است؛ از RF یا GB همراه بازبینی دامنه استفاده کنید.",
            ),
        },
        "de": {
            "Document assumptions and choose an analysis plan": (
                "Annahmen dokumentieren und Analyseplan wählen",
                "Wenige Fehlwerte beweisen MCAR nicht; legen Sie die Analyse vorab fest und prüfen Sie die fachliche Plausibilität einer Complete-Case-Analyse.",
            ),
            "Multiple imputation or model-based analysis + sensitivity analysis": (
                "Multiple Imputation oder modellbasierte Analyse mit Sensitivitätsanalyse",
                "Wählen Sie das Modell anhand fachlicher Kenntnisse und prüfen Sie die Sensitivität gegenüber Annahmen zu fehlenden Werten.",
            ),
            "Multiple imputation + sensitivity analysis + domain review": (
                "Multiple Imputation, Sensitivitätsanalyse und fachliche Prüfung",
                "Viele Fehlwerte erfordern einen dokumentierten Analyseplan, fachliche Prüfung und Sensitivitätsanalyse; beobachtete Daten können MNAR nicht ausschließen.",
            ),
            "Complete-case analysis or mean/median imputation": (
                "Vollständige Fälle oder Mittelwert-/Median-Imputation",
                "Die Fehlwerte sind MCAR und selten; das Entfernen betroffener Zeilen verursacht voraussichtlich keine relevante Verzerrung.",
            ),
            "KNN or MICE imputation": (
                "KNN- oder MICE-Imputation",
                "Die Fehlwerte sind MCAR, aber moderat; KNN oder MICE erhält mehr statistische Struktur.",
            ),
            "MICE imputation + sensitivity analysis": (
                "MICE-Imputation mit Sensitivitätsanalyse",
                "Die Fehlwerte sind MCAR, aber häufig; verwenden Sie MICE und führen Sie eine Sensitivitätsanalyse durch.",
            ),
            "MICE or Random Forest imputation": (
                "MICE- oder Random-Forest-Imputation",
                "Die Fehlwerte sind nicht MCAR; modellbasierte Imputation mit MICE oder Random Forest wird empfohlen.",
            ),
            "Random Forest or Gradient Boosting imputation + domain review": (
                "Random Forest oder Gradient Boosting mit fachlicher Prüfung",
                "Die Fehlwerte sind nicht MCAR und häufig; verwenden Sie RF oder GB mit fachlicher Prüfung.",
            ),
        },
    }
    localized = recommendation_translations.get(lang, {}).get(recommendation)
    if localized is not None:
        recommendation, recommendation_detail = localized

    return {
        "mechanism": mechanism,
        "mechanism_detail": mechanism_detail,
        "recommendation": recommendation,
        "recommendation_detail": recommendation_detail,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def create_report(
    df: pd.DataFrame,
    output_path: str = "missing_data_report.html",
    title: str = "Missing Data Analysis Report",
    missing_values: Optional[list] = None,
    language: str = "en",
) -> str:
    """Generate a self-contained HTML report for missing data analysis.

    Parameters
    ----------
    df : pd.DataFrame
    output_path : str, optional
    title : str, optional
    missing_values : list, optional
    language : str, optional

    Returns
    -------
    str
        Absolute path to the saved HTML file.
    """
    if df.empty:
        raise ValueError("Cannot generate a report for an empty DataFrame.")

    if language not in _SUPPORTED_LANGUAGES:
        warnings.warn(
            f"Language {language!r} is not supported; falling back to 'en'. "
            f"Supported: {sorted(_SUPPORTED_LANGUAGES)}",
            UserWarning,
            stacklevel=2,
        )
        language = "en"

    labels = _get_labels(language)
    text_dir = "rtl" if language in _RTL_LANGUAGES else "ltr"
    text_align = "right" if language in _RTL_LANGUAGES else "left"

    df_analysis = df.copy()
    if missing_values:
        df_analysis = df_analysis.replace(missing_values, pd.NA)

    n_rows, n_cols = df_analysis.shape
    total_miss = n_miss(df_analysis)
    overall_pct = pct_miss(df_analysis)
    no_missing = total_miss == 0

    # Build per-column overview rows for the template table
    overview_rows = []
    for col in df_analysis.columns:
        col_miss = int(df_analysis[col].isnull().sum())
        col_pct = float(df_analysis[col].isnull().mean() * 100)
        if col_pct == 0:
            severity_class, severity_label = "none", "None"
        elif col_pct < 5:
            severity_class, severity_label = "low", "Low"
        elif col_pct < 20:
            severity_class, severity_label = "medium", "Medium"
        else:
            severity_class, severity_label = "high", "High"
        overview_rows.append({
            "column": col,
            "missing": col_miss,
            "pct": col_pct,
            "dtype": str(df_analysis[col].dtype),
            "severity_class": severity_class,
            "severity_label": severity_label,
        })

    # Summary stats dict for the template
    summary = {
        "total_cells": n_rows * n_cols,
        "missing_cells": int(total_miss),
        "pct_missing": float(overall_pct),
        "cols_any_missing": int(df_analysis.isnull().any(axis=0).sum()),
        "rows_any_missing": int(df_analysis.isnull().any(axis=1).sum()),
        "complete_rows": int((~df_analysis.isnull().any(axis=1)).sum()),
    }

    cases = miss_case_summary(df_analysis)
    cases = cases.loc[cases["n_miss"] > 0].nlargest(10, "n_miss")
    cases_rows = [
        {
            "index": row.case,
            "missing": int(row.n_miss),
            "pct": float(row.pct_miss),
        }
        for row in cases.itertuples(index=False)
    ]

    mcar_result = None
    mcar_info = None
    numeric_analysis = df_analysis.select_dtypes(include=[np.number])
    # Little's MCAR test cannot estimate moments for columns containing no
    # observed values.  Such columns remain visible in every descriptive
    # section of the report, but are excluded from this inferential test.
    numeric_analysis = numeric_analysis.loc[
        :, numeric_analysis.notna().any(axis=0)
    ]
    if not numeric_analysis.empty and numeric_analysis.isnull().any(axis=None):
        try:
            mcar_result = mcar_test(numeric_analysis)
            mcar_info = _mcar_interpretation(
                mcar_result["p_value"], overall_pct, lang=language
            )
        except (ValueError, TypeError, np.linalg.LinAlgError, ArithmeticError) as exc:
            warnings.warn(f"MCAR test failed: {exc}", UserWarning, stacklevel=2)

    matrix_plot  = _safe_plot(matrix,   df_analysis)
    bar_plot     = _safe_plot(bar,      df_analysis)
    heatmap_plot = _safe_plot(heatmap,  df_analysis)
    vismiss_plot = _safe_plot(vis_miss, df_analysis)
    upset_plot   = _safe_plot(upset,    df_analysis)

    import os
    templates_dir = os.path.join(os.path.dirname(__file__), "templates")
    env = Environment(loader=FileSystemLoader(templates_dir), autoescape=True)
    template = env.get_template("report.html")

    html = template.render(
        title=title,
        language=language,
        lang=language,
        dir=text_dir,
        text_dir=text_dir,
        text_align=text_align,
        labels=labels,
        no_missing=no_missing,
        overview_rows=overview_rows,
        cases_rows=cases_rows,
        summary=summary,
        mcar_result=mcar_result,
        mcar_info=mcar_info,
        matrix_plot=matrix_plot,
        bar_plot=bar_plot,
        heatmap_plot=heatmap_plot,
        vismiss_plot=vismiss_plot,
        upset_plot=upset_plot,
    )

    output_path = os.path.abspath(output_path)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    return output_path
