"""HTML report generation for missing data analysis.

This module provides :func:`create_report`, which generates a
self-contained, standalone HTML report summarising all aspects of
missingness in a DataFrame:

1. **Dataset overview** — shape, total missing count, percentage.
2. **Per-variable summary** — n_miss, pct_miss for every column.
3. **Per-case summary** — top 10 rows with the most missing values.
4. **MCAR test result** — Little's test chi-square, df, p-value, and a
   plain-English interpretation.
5. **Imputation recommendation** — based on MCAR test result and
   missingness fraction, a concrete recommendation is provided.
6. **Visualisations** — matrix, bar, heatmap, and vis_miss plots,
   embedded as base64 PNG images (no external dependencies).

All plots are generated with a non-interactive Matplotlib backend so the
function works correctly in headless CI environments and notebooks alike.

Compatibility
-------------
Requires Python 3.9+, pandas 2.0+, matplotlib, and jinja2.
"""

from __future__ import annotations

import base64
import warnings
from io import BytesIO
from typing import Optional

import matplotlib
matplotlib.use("Agg")  # headless backend — must be set before pyplot import
import matplotlib.pyplot as plt
import pandas as pd

from jinja2 import Environment, FileSystemLoader

from .summary import miss_var_summary, miss_case_summary, n_miss, pct_miss
from .visualise import matrix, bar, heatmap, vis_miss
from .stats import mcar_test


# ---------------------------------------------------------------------------
# i18n: UI label translations
#
# Rule: statistical / technical terms are kept in English in every language.
# This includes: MCAR, MAR, MNAR, MICE, KNN, p-value, Chi-square,
# Little's Test, Random Forest, Gradient Boosting, sensitivity analysis.
# Only surrounding descriptive prose is translated.
# ---------------------------------------------------------------------------

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        # Section headings
        "section_overview":        "Dataset Overview",
        "section_variables":       "Missing Values by Variable",
        "section_cases":           "Top 10 Rows by Missingness",
        "section_mcar":            "MCAR Test (Little\u2019s Test)",
        "section_recommendation":  "Imputation Recommendation",
        "section_plots":           "Visualisations",
        # Overview card labels
        "card_rows":               "Rows",
        "card_cols":               "Columns",
        "card_total_cells":        "Total Cells",
        "card_missing_cells":      "Missing Cells",
        "card_pct_missing":        "% Missing",
        # MCAR stat labels
        "stat_chi_square":         "Chi-square",
        "stat_df":                 "Degrees of Freedom",
        "stat_p_value":            "p-value",
        "stat_patterns":           "Missing Patterns",
        # Plot titles
        "plot_matrix":             "Missingness Matrix",
        "plot_bar":                "Missing Values per Column",
        "plot_heatmap":            "Missingness Correlation Heatmap",
        "plot_vismiss":            "Missing Pattern Overview",
        # Misc
        "no_missing":              "\u2713 No missing values detected in this DataFrame.",
        "generated_by":            "Generated by",
        "recommendation_icon":     "\U0001f4a1",
    },
    "fa": {
        "section_overview":        "\u062e\u0644\u0627\u0635\u0647 \u0645\u062c\u0645\u0648\u0639\u0647 \u062f\u0627\u062f\u0647",
        "section_variables":       "\u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628 \u0628\u0647 \u062a\u0641\u06a9\u06cc\u06a9 \u0645\u062a\u063a\u06cc\u0631",
        "section_cases":           "\u06f1\u06f0 \u0633\u0637\u0631 \u0628\u0627 \u0628\u06cc\u0634\u062a\u0631\u06cc\u0646 \u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628",
        "section_mcar":            "\u0622\u0632\u0645\u0648\u0646 MCAR (Little\u2019s Test)",
        "section_recommendation":  "\u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u062c\u0627\u06cc\u06af\u0632\u06cc\u0646\u06cc",
        "section_plots":           "\u0646\u0645\u0648\u062f\u0627\u0631\u0647\u0627",
        "card_rows":               "\u062a\u0639\u062f\u0627\u062f \u0633\u0637\u0631\u0647\u0627",
        "card_cols":               "\u062a\u0639\u062f\u0627\u062f \u0633\u062a\u0648\u0646\u0647\u0627",
        "card_total_cells":        "\u06a9\u0644 \u062e\u0627\u0646\u0647\u0647\u0627",
        "card_missing_cells":      "\u062e\u0627\u0646\u0647\u0647\u0627\u06cc \u063a\u0627\u06cc\u0628",
        "card_pct_missing":        "\u062f\u0631\u0635\u062f \u063a\u06cc\u0628\u062a",
        "stat_chi_square":         "Chi-square",
        "stat_df":                 "\u062f\u0631\u062c\u0627\u062a \u0622\u0632\u0627\u062f\u06cc",
        "stat_p_value":            "p-value",
        "stat_patterns":           "\u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a",
        "plot_matrix":             "\u0645\u0627\u062a\u0631\u06cc\u0633 \u063a\u06cc\u0628\u062a",
        "plot_bar":                "\u0645\u0642\u0627\u062f\u06cc\u0631 \u063a\u0627\u06cc\u0628 \u0628\u0647 \u0627\u0632\u0627\u06cc \u0633\u062a\u0648\u0646",
        "plot_heatmap":            "\u0647\u0645\u0628\u0633\u062a\u06af\u06cc \u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a",
        "plot_vismiss":            "\u0646\u0645\u0627\u06cc \u06a9\u0644\u06cc \u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a",
        "no_missing":              "\u2713 \u0647\u06cc\u0686 \u0645\u0642\u062f\u0627\u0631 \u063a\u0627\u06cc\u0628\u06cc \u062f\u0631 \u0627\u06cc\u0646 DataFrame \u06cc\u0627\u0641\u062a \u0646\u0634\u062f.",
        "generated_by":            "\u062a\u0648\u0644\u06cc\u062f\u0634\u062f\u0647 \u062a\u0648\u0633\u0637",
        "recommendation_icon":     "\U0001f4a1",
    },
    "de": {
        "section_overview":        "Datensatz\u00fcbersicht",
        "section_variables":       "Fehlende Werte nach Variable",
        "section_cases":           "Top 10 Zeilen nach Fehlenden Werten",
        "section_mcar":            "MCAR-Test (Little\u2019s Test)",
        "section_recommendation":  "Imputationsempfehlung",
        "section_plots":           "Visualisierungen",
        "card_rows":               "Zeilen",
        "card_cols":               "Spalten",
        "card_total_cells":        "Zellen gesamt",
        "card_missing_cells":      "Fehlende Zellen",
        "card_pct_missing":        "% Fehlend",
        "stat_chi_square":         "Chi-Quadrat",
        "stat_df":                 "Freiheitsgrade",
        "stat_p_value":            "p-Wert",
        "stat_patterns":           "Fehlende Muster",
        "plot_matrix":             "Fehlende-Werte-Matrix",
        "plot_bar":                "Fehlende Werte pro Spalte",
        "plot_heatmap":            "Korrelations-Heatmap der Fehlenden",
        "plot_vismiss":            "Muster\u00fcbersicht",
        "no_missing":              "\u2713 Keine fehlenden Werte in diesem DataFrame gefunden.",
        "generated_by":            "Erstellt von",
        "recommendation_icon":     "\U0001f4a1",
    },
}

_RTL_LANGUAGES: frozenset[str] = frozenset({"fa", "ar", "he", "ur"})
_SUPPORTED_LANGUAGES: frozenset[str] = frozenset(_TRANSLATIONS)


def _get_labels(language: str) -> dict[str, str]:
    """Return UI label dict for *language*, falling back to English."""
    return _TRANSLATIONS.get(language, _TRANSLATIONS["en"])


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _fig_to_b64(fig: plt.Figure) -> str:
    """Encode a Matplotlib Figure as a base64 PNG string.

    Parameters
    ----------
    fig : matplotlib.figure.Figure
        The figure to encode.

    Returns
    -------
    str
        Base64-encoded PNG data (suitable for inline ``<img>`` src).
    """
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=120)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def _safe_plot(plot_fn, df: pd.DataFrame, **kwargs) -> Optional[str]:
    """Call a plot function and return a base64 PNG, or None on failure.

    Swallows exceptions so a single failed visualisation does not crash
    the entire report.

    Parameters
    ----------
    plot_fn : callable
        A missingly visualisation function that accepts *df* and returns
        a Matplotlib Axes.
    df : pd.DataFrame
        DataFrame to visualise.
    **kwargs
        Additional keyword arguments forwarded to *plot_fn*.

    Returns
    -------
    str or None
        Base64-encoded PNG string, or ``None`` if the plot failed.
    """
    try:
        fig, ax = plt.subplots(figsize=(10, 4))
        plot_fn(df, ax=ax, **kwargs)
        b64 = _fig_to_b64(fig)
        plt.close(fig)
        return b64
    except Exception as exc:  # noqa: BLE001
        warnings.warn(f"Plot {plot_fn.__name__!r} failed: {exc}", UserWarning, stacklevel=2)
        plt.close("all")
        return None


def _mcar_interpretation(p_value: float, overall_pct: float, lang: str = "en") -> dict:
    """Produce an MCAR interpretation and imputation recommendation.

    Statistical terminology (MCAR, MAR, MNAR, MICE, KNN, p-value,
    Chi-square, Little\u2019s Test, Random Forest, Gradient Boosting) is kept
    in English regardless of *lang*.  Only surrounding descriptive prose
    is translated.

    Parameters
    ----------
    p_value : float
        p-value from Little\u2019s MCAR test.
    overall_pct : float
        Overall percentage of missing values in the DataFrame.
    lang : str, optional
        ISO 639-1 language code.  Supported: ``"en"``, ``"fa"``, ``"de"``.
        Unknown codes fall back to ``"en"``.

    Returns
    -------
    dict
        Keys: ``mechanism``, ``mechanism_detail``,
        ``recommendation``, ``recommendation_detail``.
    """
    import math

    is_fa = lang == "fa"
    is_de = lang == "de"

    # ------------------------------------------------------------------
    # Mechanism
    # ------------------------------------------------------------------
    if math.isnan(p_value):
        mechanism = "Unknown"
        if is_fa:
            mechanism_detail = (
                "\u0622\u0632\u0645\u0648\u0646 MCAR \u0642\u0627\u0628\u0644 \u0645\u062d\u0627\u0633\u0628\u0647 \u0646\u0628\u0648\u062f "
                "(\u062f\u0627\u062f\u0647 \u06a9\u0627\u0641\u06cc \u0646\u06cc\u0633\u062a \u06cc\u0627 \u0641\u0642\u0637 \u06cc\u06a9 \u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a \u0648\u062c\u0648\u062f \u062f\u0627\u0631\u062f). "
                "\u0633\u0627\u0632\u0648\u06a9\u0627\u0631 \u0646\u0627\u0645\u0634\u062e\u0635 \u0641\u0631\u0636 \u06a9\u0646\u06cc\u062f."
            )
        elif is_de:
            mechanism_detail = (
                "Der MCAR-Test konnte nicht berechnet werden "
                "(unzureichende Daten oder nur ein fehlendes Muster). "
                "Behandeln Sie den Mechanismus als unbekannt."
            )
        else:
            mechanism_detail = (
                "The MCAR test could not be computed (insufficient data or "
                "only one missing pattern). Treat the mechanism as unknown."
            )

    elif p_value > 0.05:
        mechanism = "MCAR (Missing Completely At Random)"
        if is_fa:
            mechanism_detail = (
                f"p = {p_value:.4f} > 0.05: \u0641\u0631\u0636\u06cc\u0647 MCAR \u0631\u062f \u0646\u0634\u062f. "
                "\u0627\u062d\u062a\u0645\u0627\u0644 \u063a\u06cc\u0628\u062a \u0628\u0647 \u0647\u06cc\u0686 \u062f\u0627\u062f\u0647 \u0645\u0634\u0627\u0647\u062f\u0647\u200c\u0634\u062f\u0647 \u06cc\u0627 \u0645\u0634\u0627\u0647\u062f\u0647\u200c\u0646\u0634\u062f\u0647\u200c\u0627\u06cc "
                "\u0628\u0633\u062a\u06af\u06cc \u0646\u062f\u0627\u0631\u062f. \u0631\u0648\u0634\u200c\u0647\u0627\u06cc \u0633\u0627\u062f\u0647 \u062c\u0627\u06cc\u06af\u0632\u06cc\u0646\u06cc "
                "\u0627\u0632 \u0646\u0638\u0631 \u0622\u0645\u0627\u0631\u06cc \u0645\u062c\u0627\u0632 \u0647\u0633\u062a\u0646\u062f."
            )
        elif is_de:
            mechanism_detail = (
                f"p = {p_value:.4f} > 0.05: MCAR kann nicht abgelehnt werden. "
                "Die Wahrscheinlichkeit eines fehlenden Werts h\u00e4ngt nicht mit "
                "beobachteten oder unbeobachteten Daten zusammen. "
                "Einfache Imputationsstrategien sind statistisch gerechtfertigt."
            )
        else:
            mechanism_detail = (
                f"p = {p_value:.4f} > 0.05: cannot reject MCAR. The probability "
                "of a value being missing is unrelated to any observed or "
                "unobserved data. Simple imputation strategies are statistically "
                "justified."
            )

    else:
        mechanism = "MAR / MNAR (Not MCAR)"
        if is_fa:
            mechanism_detail = (
                f"p = {p_value:.4f} \u2264 0.05: \u0641\u0631\u0636\u06cc\u0647 MCAR \u0631\u062f \u0634\u062f. "
                "\u0627\u0644\u06af\u0648\u06cc \u063a\u06cc\u0628\u062a \u0628\u0647 \u062f\u0627\u062f\u0647\u200c\u0647\u0627 \u0648\u0627\u0628\u0633\u062a\u0647 \u0627\u0633\u062a. "
                "\u062c\u0627\u06cc\u06af\u0632\u06cc\u0646\u06cc \u0633\u0627\u062f\u0647 (\u0645\u06cc\u0627\u0646\u06af\u06cc\u0646/\u0645\u062f\u06cc\u0627\u0646) "
                "\u0645\u06cc\u200c\u062a\u0648\u0627\u0646\u062f \u0627\u0646\u062d\u0631\u0627\u0641 \u0627\u06cc\u062c\u0627\u062f \u06a9\u0646\u062f\u061b "
                "\u0631\u0648\u0634\u200c\u0647\u0627\u06cc \u0645\u0628\u062a\u0646\u06cc \u0628\u0631 \u0645\u062f\u0644 \u0627\u0631\u062c\u062d \u062f\u0627\u0631\u0646\u062f."
            )
        elif is_de:
            mechanism_detail = (
                f"p = {p_value:.4f} \u2264 0.05: MCAR wird abgelehnt. Das Fehlendmuster "
                "h\u00e4ngt mit den Daten zusammen. Einfache Mittelwert-/Medianimputation "
                "kann Verzerrungen einf\u00fchren; modellbasierte Methoden werden empfohlen."
            )
        else:
            mechanism_detail = (
                f"p = {p_value:.4f} \u2264 0.05: MCAR is rejected. The pattern of "
                "missingness is related to the data. Simple mean/median "
                "imputation may introduce bias; model-based methods are preferred."
            )

    # ------------------------------------------------------------------
    # Recommendation (method names stay in English; prose is translated)
    # ------------------------------------------------------------------
    if math.isnan(p_value) or p_value > 0.05:
        if overall_pct < 5:
            recommendation = "Complete-case analysis or mean/median imputation"
            if is_fa:
                recommendation_detail = (
                    "\u063a\u06cc\u0628\u062a MCAR \u0648 \u06a9\u0645 \u0627\u0633\u062a (< 5%). "
                    "\u062d\u0630\u0641 \u0633\u0637\u0631\u0647\u0627\u06cc \u063a\u0627\u06cc\u0628 \u06cc\u0627 \u062c\u0627\u06cc\u06af\u0632\u06cc\u0646\u06cc "
                    "\u0628\u0627 \u0645\u06cc\u0627\u0646\u06af\u06cc\u0646/\u0645\u062f\u06cc\u0627\u0646 \u062a\u0627\u062b\u06cc\u0631 \u0645\u0639\u0646\u06cc\u200c\u062f\u0627\u0631\u06cc "
                    "\u0628\u0631 \u0646\u062a\u0627\u06cc\u062c \u0646\u062e\u0648\u0627\u0647\u062f \u062f\u0627\u0634\u062a."
                )
            elif is_de:
                recommendation_detail = (
                    "MCAR und geringe Fehlquote (< 5%). Vollst\u00e4ndige F\u00e4lle oder "
                    "Mittelwert-/Medianimputation f\u00fchren zu keiner bedeutsamen Verzerrung."
                )
            else:
                recommendation_detail = (
                    "Missingness is MCAR and low (< 5%). Dropping rows with "
                    "missing values or using mean/median imputation will not "
                    "meaningfully bias results."
                )
        elif overall_pct < 20:
            recommendation = "KNN or MICE imputation"
            if is_fa:
                recommendation_detail = (
                    "\u063a\u06cc\u0628\u062a MCAR \u0648 \u0645\u062a\u0648\u0633\u0637 \u0627\u0633\u062a (5\u201320%). "
                    "KNN \u06cc\u0627 MICE \u0633\u0627\u062e\u062a\u0627\u0631 \u0622\u0645\u0627\u0631\u06cc "
                    "\u0628\u06cc\u0634\u062a\u0631\u06cc \u0646\u0633\u0628\u062a \u0628\u0647 \u0645\u06cc\u0627\u0646\u06af\u06cc\u0646/\u0645\u062f\u06cc\u0627\u0646 \u062d\u0641\u0638 \u0645\u06cc\u200c\u06a9\u0646\u0646\u062f."
                )
            elif is_de:
                recommendation_detail = (
                    "MCAR, aber moderate Fehlquote (5\u201320%). KNN oder MICE "
                    "erhalten mehr statistische Struktur als Mittelwert-/Medianimputation."
                )
            else:
                recommendation_detail = (
                    "Missingness is MCAR but moderate (5\u201320%). KNN or MICE "
                    "preserves more statistical structure than mean/median."
                )
        else:
            recommendation = "MICE imputation + sensitivity analysis"
            if is_fa:
                recommendation_detail = (
                    "\u063a\u06cc\u0628\u062a MCAR \u0627\u0633\u062a \u0627\u0645\u0627 \u0632\u06cc\u0627\u062f (\u2265 20%). "
                    "\u0627\u0632 MICE \u0627\u0633\u062a\u0641\u0627\u062f\u0647 \u06a9\u0646\u06cc\u062f \u0648 "
                    "\u06cc\u06a9 sensitivity analysis \u0627\u0646\u062c\u0627\u0645 \u062f\u0647\u06cc\u062f."
                )
            elif is_de:
                recommendation_detail = (
                    "MCAR, aber hohe Fehlquote (\u2265 20%). MICE verwenden und eine "
                    "Sensitivit\u00e4tsanalyse durchf\u00fchren."
                )
            else:
                recommendation_detail = (
                    "Missingness is MCAR but high (\u2265 20%). Use MICE and run a "
                    "sensitivity analysis to check how much imputation choices "
                    "affect your downstream results."
                )
    else:
        if overall_pct < 20:
            recommendation = "MICE or Random Forest imputation"
            if is_fa:
                recommendation_detail = (
                    "\u063a\u06cc\u0628\u062a MCAR \u0646\u06cc\u0633\u062a. "
                    "\u062c\u0627\u06cc\u06af\u0632\u06cc\u0646\u06cc \u0645\u0628\u062a\u0646\u06cc \u0628\u0631 \u0645\u062f\u0644 (MICE\u060c Random Forest) "
                    "\u0628\u0647\u062a\u0631 \u0627\u0633\u062a \u0632\u06cc\u0631\u0627 \u0627\u0632 \u0647\u0645\u0628\u0633\u062a\u06af\u06cc "
                    "\u0628\u06cc\u0646 \u0645\u062a\u063a\u06cc\u0631\u0647\u0627 \u0628\u0647\u0631\u0647 \u0645\u06cc\u200c\u06af\u06cc\u0631\u062f."
                )
            elif is_de:
                recommendation_detail = (
                    "Nicht MCAR. Modellbasierte Imputation (MICE, Random Forest) "
                    "ist empfohlen, da sie Korrelationen zwischen Variablen nutzt."
                )
            else:
                recommendation_detail = (
                    "Missingness is not MCAR. Model-based imputation (MICE, RF, GB) "
                    "is recommended as it can leverage correlations between variables "
                    "to produce less biased imputations."
                )
        else:
            recommendation = "Random Forest or Gradient Boosting imputation + domain review"
            if is_fa:
                recommendation_detail = (
                    "\u063a\u06cc\u0628\u062a MCAR \u0646\u06cc\u0633\u062a \u0648 \u0632\u06cc\u0627\u062f (\u2265 20%). "
                    "\u0627\u0632 Random Forest \u06cc\u0627 Gradient Boosting \u0627\u0633\u062a\u0641\u0627\u062f\u0647 \u06a9\u0646\u06cc\u062f. "
                    "\u0647\u0645\u0686\u0646\u06cc\u0646 \u0628\u0631\u0631\u0633\u06cc \u06a9\u0646\u06cc\u062f \u06a9\u0647 \u0622\u06cc\u0627 \u063a\u06cc\u0628\u062a \u0632\u06cc\u0627\u062f "
                    "\u0646\u0634\u0627\u0646\u200c\u062f\u0647\u0646\u062f\u0647 \u06cc\u06a9 \u0645\u0634\u06a9\u0644 \u062f\u0631 \u062c\u0645\u0639\u200c\u0622\u0648\u0631\u06cc \u062f\u0627\u062f\u0647 \u0627\u0633\u062a."
                )
            elif is_de:
                recommendation_detail = (
                    "Nicht MCAR und hohe Fehlquote (\u2265 20%). Random Forest oder "
                    "Gradient Boosting verwenden. Pr\u00fcfen Sie zus\u00e4tzlich, ob die "
                    "hohe Fehlquote auf ein Datenerhebungsproblem hinweist."
                )
            else:
                recommendation_detail = (
                    "Missingness is not MCAR and is high (\u2265 20%). Use RF or GB "
                    "imputation. Additionally, consider whether the high missingness "
                    "indicates a data collection problem that should be fixed upstream."
                )

    return {
        "mechanism": mechanism,
        "mechanism_detail": mechanism_detail,
        "recommendation": recommendation,
        "recommendation_detail": recommendation_detail,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def create_report(
    df: pd.DataFrame,
    output_path: str = "missing_data_report.html",
    title: str = "Missing Data Analysis Report",
    missing_values: Optional[list] = None,
    language: str = "en",
) -> str:
    """Generate a self-contained HTML report for missing data analysis.

    The report includes:

    1. **Dataset overview** (shape, total missing, overall pct missing).
    2. **Per-variable summary table** (n_miss, pct_miss per column).
    3. **Per-case summary** (top 10 most-missing rows).
    4. **MCAR test** (chi-square, df, p-value, interpretation).
    5. **Imputation recommendation** (concrete, based on MCAR result and
       missingness fraction).
    6. **Visualisations** (matrix, bar chart, heatmap, vis_miss heatmap),
       all embedded as inline base64 images.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to analyse.  May contain missing values.
    output_path : str, optional
        File path where the HTML report is saved.  Default is
        ``"missing_data_report.html"`` in the current directory.
    title : str, optional
        Title displayed at the top of the HTML report.
    missing_values : list, optional
        Additional sentinel values treated as missing (e.g. ``[-99, "N/A"]``).
        These are replaced with ``NaN`` before any analysis.
    language : str, optional
        ISO 639-1 language code for the report UI.  Supported values:
        ``"en"`` (default), ``"fa"`` (Persian/Farsi \u2014 RTL layout),
        ``"de"`` (German).  Unknown codes fall back to ``"en"`` with a
        ``UserWarning``.  Statistical terminology (MCAR, MICE, KNN,
        p-value, etc.) is always kept in English regardless of this setting.

    Returns
    -------
    str
        The absolute path to the saved HTML file.

    Raises
    ------
    ValueError
        If *df* is empty.

    Example
    -------
    >>> import pandas as pd, numpy as np
    >>> df = pd.DataFrame({'age': [25, np.nan, 35], 'city': ['A', None, 'C']})
    >>> create_report(df, output_path='/tmp/report_fa.html', language='fa')
    '/tmp/report_fa.html'
    """
    if df.empty:
        raise ValueError("Cannot generate a report for an empty DataFrame.")

    if language not in _SUPPORTED_LANGUAGES:
        warnings.warn(
            f"Language {language!r} is not supported; falling back to 'en'. "
            f"Supported: {sorted(_SUPPORTED_LANGUAGES)}",
            UserWarning,
            stacklevel=2,
        )
        language = "en"

    labels = _get_labels(language)
    text_dir = "rtl" if language in _RTL_LANGUAGES else "ltr"

    # Replace extra sentinels
    df_analysis = df.copy()
    if missing_values:
        df_analysis = df_analysis.replace(missing_values, pd.NA)

    # ---------------------------------------------------------------
    # 1. Dataset overview
    # ---------------------------------------------------------------
    n_rows, n_cols = df_analysis.shape
    total_miss = n_miss(df_analysis)
    overall_pct = pct_miss(df_analysis)
    overview = {
        "rows": n_rows,
        "cols": n_cols,
        "total_cells": n_rows * n_cols,
        "total_missing": total_miss,
        "overall_pct_missing": f"{overall_pct:.2f}%",
    }

    # ---------------------------------------------------------------
    # 2. Per-variable summary
    # ---------------------------------------------------------------
    var_summary_html = (
        miss_var_summary(df_analysis)
        .sort_values("pct_miss", ascending=False)
        .style
        .format({"pct_miss": "{:.2f}"})
        .set_table_attributes('class="summary-table"')
        .to_html()
    )

    # ---------------------------------------------------------------
    # 3. Per-case summary (top 10)
    # ---------------------------------------------------------------
    case_summary_html = (
        miss_case_summary(df_analysis)
        .sort_values("n_miss", ascending=False)
        .head(10)
        .style
        .format({"pct_miss": "{:.2f}"})
        .set_table_attributes('class="summary-table"')
        .to_html()
    )

    # ---------------------------------------------------------------
    # 4. MCAR test
    # ---------------------------------------------------------------
    mcar_result = None
    mcar_info = None
    try:
        mcar_result = mcar_test(df_analysis)
        mcar_info = _mcar_interpretation(mcar_result.p_value, overall_pct, lang=language)
    except Exception as exc:  # noqa: BLE001
        warnings.warn(f"MCAR test failed: {exc}", UserWarning, stacklevel=2)

    # ---------------------------------------------------------------
    # 5. Visualisations
    # ---------------------------------------------------------------
    matrix_plot  = _safe_plot(matrix,   df_analysis)
    bar_plot     = _safe_plot(bar,      df_analysis)
    heatmap_plot = _safe_plot(heatmap,  df_analysis)
    vismiss_plot = _safe_plot(vis_miss, df_analysis)

    # ---------------------------------------------------------------
    # 6. Render template
    # ---------------------------------------------------------------
    import os
    templates_dir = os.path.join(os.path.dirname(__file__), "templates")
    env = Environment(loader=FileSystemLoader(templates_dir), autoescape=True)
    template = env.get_template("report.html")

    html = template.render(
        title=title,
        language=language,
        text_dir=text_dir,
        labels=labels,
        overview=overview,
        var_summary=var_summary_html,
        case_summary=case_summary_html,
        mcar_result=mcar_result,
        mcar_info=mcar_info,
        matrix_plot=matrix_plot,
        bar_plot=bar_plot,
        heatmap_plot=heatmap_plot,
        vismiss_plot=vismiss_plot,
    )

    output_path = os.path.abspath(output_path)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    return output_path
