"""Validate scalar R oracle evidence against the committed benchmark manifest."""

from __future__ import annotations

import json
from pathlib import Path
import sys


_METRIC_MAP = {
    "chi_square": "chi_square",
    "degrees_of_freedom": "degrees_of_freedom",
    "p_value": "p_value",
    "missing_patterns": "missing_patterns",
}


def main(reference_path: Path, manifest_path: Path) -> None:
    """Fail when locked R evidence differs from the reviewed scalar oracle.

    Parameters
    ----------
    reference_path : pathlib.Path
        JSON artifact emitted by ``generate_naniar_reference.R``.
    manifest_path : pathlib.Path
        Reviewed benchmark manifest that defines scalar oracle tolerances.

    Raises
    ------
    ValueError
        If tool identity, data identity, source-script identity, or a scalar
        metric fails the committed evidence contract.

    Examples
    --------
    >>> from pathlib import Path
    >>> # The CI workflow supplies reviewed paths for both arguments.
    >>> isinstance(Path("reference.json"), Path)
    True
    """
    reference = json.loads(reference_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if reference["dataset_sha256"] != manifest["dataset_sha256"]:
        raise ValueError("R reference dataset SHA-256 does not match benchmark manifest")
    if reference["reference_tool"] != "R naniar":
        raise ValueError("R reference was not generated by the expected tool")
    if not reference["source_script_sha256"] or reference["source_script_sha256"] == "unrecorded":
        raise ValueError("R reference is missing its source-script SHA-256")

    expected = manifest["expected_metrics"]
    tolerances = manifest["tolerances"]
    for reference_name, manifest_name in _METRIC_MAP.items():
        actual = float(reference["metrics"][reference_name])
        target = float(expected[manifest_name])
        tolerance = float(tolerances[manifest_name])
        if abs(actual - target) > tolerance:
            raise ValueError(
                f"{reference_name} differs from committed oracle: "
                f"actual={actual}, expected={target}, tolerance={tolerance}"
            )


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(
            "Usage: validate_naniar_reference.py <reference.json> <manifest.json>"
        )
    main(Path(sys.argv[1]), Path(sys.argv[2]))
