# manual_tests/test_visualise_manual.py

import os

import matplotlib.pyplot as plt
import pandas as pd

from missingly import visualise

OUTPUT_DIR = "manual_tests/output_visualization/"

def load_data():
    """
    Generated by:
    manual_tests/generate_petrochemical_sensors.py
    """
    df = pd.read_csv(
        ".\manual_tests\petrochemical_tank_sensors.csv",
        parse_dates=["زمان ثبت"],
    )

    # برای تست‌های دستی سریع‌تر
    if len(df) > 10000:
        df = df.sample(
            n=10000,
            random_state=42,
        )

    return df


def save_plot(name):
    plt.tight_layout()
    plt.savefig(
        OUTPUT_DIR + f"{name}.png",
        dpi=150,
        bbox_inches="tight",
    )
    plt.close()


def test_matrix(df):
    visualise.matrix(df)
    save_plot("matrix")


def test_vis_miss(df):
    visualise.vis_miss(
        df,
        show_pct=True,
        cluster=True,
    )
    save_plot("vis_miss")


def test_bar(df):
    visualise.bar(df)
    save_plot("bar")


def test_miss_case(df):
    visualise.miss_case(df)
    save_plot("miss_case")


def test_miss_var_pct(df):
    visualise.miss_var_pct(df)
    save_plot("miss_var_pct")


def test_miss_which(df):
    visualise.miss_which(df)
    save_plot("miss_which")


def test_upset(df):
    visualise.upset(
        df,
        max_patterns=15,
    )

    plt.savefig(
        OUTPUT_DIR + "upset.png",
        dpi=150,
        bbox_inches="tight",
    )

    plt.close("all")


def test_miss_patterns(df):
    visualise.miss_patterns(
        df,
        top_n=15,
    )
    save_plot("miss_patterns")


def test_miss_cooccurrence(df):
    visualise.miss_cooccurrence(df)
    save_plot("miss_cooccurrence")


def test_heatmap(df):
    visualise.heatmap(df)
    save_plot("heatmap")


def test_dendrogram(df):
    visualise.dendrogram(df)
    save_plot("dendrogram")


def test_miss_cluster(df):
    visualise.miss_cluster(df)
    save_plot("miss_cluster")


def test_miss_row_profile(df):
    visualise.miss_row_profile(df)
    save_plot("miss_row_profile")


def test_shadow_scatter(df):
    visualise.shadow_scatter(
        df,
        x="دما (سانتی‌گراد)",
        y="فشار (bar)",
        shadow_col="PH",
    )
    save_plot("shadow_scatter")


def test_vis_miss_fct(df):
    visualise.vis_miss_fct(
        df,
        fct="نوع محصول",
    )
    save_plot("vis_miss_fct")


def test_vis_miss_by_group(df):
    visualise.vis_miss_by_group(
        df,
        group_col="نوع محصول",
    )
    save_plot("vis_miss_by_group")


def test_interactive(df):
    fig = visualise.matrix(
        df,
        interactive=True,
    )

    fig.write_html(
       OUTPUT_DIR + "matrix_interactive.html"
    )

    fig = visualise.heatmap(
        df,
        interactive=True,
    )

    fig.write_html(
        OUTPUT_DIR + "heatmap_interactive.html"
    )

    fig = visualise.upset(
        df,
        interactive=True,
    )

    fig.write_html(
       OUTPUT_DIR + "upset_interactive.html"
    )


def main():
    os.makedirs(
        OUTPUT_DIR,
        exist_ok=True,
    )

    df = load_data()

    print("=" * 80)
    print("Dataset Shape:", df.shape)
    print()
    print(df.isna().sum())
    print("=" * 80)

    test_matrix(df)
    test_vis_miss(df)
    test_bar(df)
    test_miss_case(df)
    test_miss_var_pct(df)
    test_miss_which(df)

    test_upset(df)
    test_miss_patterns(df)
    test_miss_cooccurrence(df)

    test_heatmap(df)
    test_dendrogram(df)
    test_miss_cluster(df)

    test_miss_row_profile(df)

    test_shadow_scatter(df)

    test_vis_miss_fct(df)
    test_vis_miss_by_group(df)

    test_interactive(df)

    print()
    print("All visualisation manual tests completed.")
    print(f"Check {OUTPUT_DIR}")


if __name__ == "__main__":
    main()